### PR TITLE
fix(http1): return 414 when URI contains more than 65534 characters

### LINKED ISSUE #2701: When the URL contains more than 65534 characters, the error code returned by Hyper is not 414.
The length of the from_shared method of the third-party library http::Uri is verified， The maximum length is (u16::MAX - 1).

### PR DESCRIPTION
**Pull request by rajing**
Previous behavior returned a 404 Bad Request. Conforms to HTTP 1.1 RFC.

Closes #2701

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -71,6 +71,7 @@ pub(super) enum Parse {
     #[cfg(feature = "http1")]
     VersionH2,
     Uri,
+    UriTooLong,
```
Comment (seanmonstar) [inline src/error.rs:74]: Perhaps the `Error::is_parse_too_large()` should return true for this variant as well?

Comment (rajing) [reply src/error.rs:74]: Thanks for the feedback. Pull request has been updated with the changes.

Comment (rajing) [reply src/error.rs:74]: Sorry, forgot to add the file. Pull request has now been updated.

File: src/error.rs [hunk 2]
```diff
@@ -152,7 +153,7 @@ impl Error {
 
     /// Returns true if this was an HTTP parse error caused by a message that was too large.
     pub fn is_parse_too_large(&self) -> bool {
-        matches!(self.inner.kind, Kind::Parse(Parse::TooLarge))
+        matches!(self.inner.kind, Kind::Parse(Parse::TooLarge) | Kind::Parse(Parse::UriTooLong))
```
Comment (seanmonstar) [inline src/error.rs:156]:
```suggestion
        matches!(
            self.inner.kind,
            Kind::Parse(Parse::TooLarge) | Kind::Parse(Parse::UriTooLong)
        )
```

**Review by seanmonstar — APPROVED** [review]
