### PR TITLE
fix(http1): only send `100 Continue` if request body is polled

### LINKED ISSUE #838: Change 100-continue behavior to send when Body has been polled
Use of the 100 (Continue) Status (https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3):

> The purpose of the 100 (Continue) status (see section 10.1.1) is to allow a client that is sending a request message with a request body to determine if the origin server is willing to accept the request (based on the request headers) before the client sends the request body. In some cases, it might either be inappropriate or highly inefficient for the client to send the body if the server will reject the message without looking at the body.

In my case, for example, I can upload file or reject already uploaded file in one atomic request.

Current state:
- 0.9.x - handler can make desigion and allow/reject client request by additional `check_continue` method. This method is not supported by https://github.com/iron/iron and https://github.com/nickel-org/nickel.rs. Also this method require duplicate logic (it not called on HTTP/1.0) for routing and check permissions;
- master - looks like this feature is forgotten.

I think, much better to send "100 Continue" status on first Body::read() call (similar logic implemented by https://github.com/frewsxcv/tiny-http project).

In this case no additional logic/callback needed for make desigion about "100 Continue":
- If you call Body::read() method, then you needs to request body and hyper send to client "100 Continue";
- If you have anought information to send final status without body, then hyper send status without "100 Continue".

I try to change logic on 0.9.x branch by send "100 Continue" status of first read call, but I failed :(

### PR DESCRIPTION
**Pull request by seanmonstar**
Before, if a client request included an `Expect: 100-continue` header,
the `100 Continue` response was sent immediately. However, this is
problematic if the service is going to reply with some 4xx status code
and reject the body.

This change delays the automatic sending of the `100 Continue` status
until the service has call `poll_data` on the request body once.

Closes #838

### CODE REVIEW

File: src/body/body.rs [hunk 1]
```diff
@@ -460,19 +469,28 @@ impl From<Cow<'static, str>> for Body {
 impl Sender {
     /// Check to see if this `Sender` can send more data.
     pub fn poll_ready(&mut self, cx: &mut task::Context<'_>) -> Poll<crate::Result<()>> {
-        match self.abort_tx.poll_canceled(cx) {
```
Comment (seanmonstar) [inline src/body/body.rs]: Seems this was important for detecting when the receiver is dropped while the connection is waiting on the socket.

**Comment by sfackler** [comment]
Does this need to be handled for http2 as well?

**Comment by seanmonstar** [comment]
Could be an enhancement, but the HTTP2 side doesn't currently have any handling of `Expect: 100-continue`. I believe sending a `RST_STREAM` is preferred there, which hyper *does* handle.

**Comment by sfackler** [comment]
Do you mean the HTTP2 standard doesn't define 100-continue semantics, or that h2 doesn't deal with it right now? RST_STREAM doesn't quite cover the same use cases, since the client doesn't have a robust way to know if it should send the body or not other than I guess waiting for a little bit to see if it gets a RST.

It seems like some implementations do support it, FWIW. Don't feel super strongly about it though: https://github.com/dotnet/corefx/issues/31312

**Comment by seanmonstar** [comment]
>  that h2 doesn't deal with it right now? 

This one. I haven't done much looking into what HTTP2 says about `expect: 100-continue`, I just figured `RST_STREAM` can serve a similar purpose, and h2 *does* handle that (a `RST_STREAM` is sent if the body is dropped).

**Comment by i110** [comment]
Do you have a plan to make the same thing possible with HTTP/2? According to HTTP specifications, an h2 server, like h1, must return a 100 continue response to `Expect: 100-continue`. Also, in practical terms beyond the spec, 100 continue allows for more precise control of body transmission timing than RST_STREAM. I need it right now and I'm thinking of creating a patch if there's no ongoing implementation or concerns. If you have any suggestions, please let me know.
