### PR TITLE
fix(http1): force always-ready connections to yield after a few spins

### LINKED ISSUE #1828: Bad tail latency: always-ready connection can starve others
We compare a [hyper hello-world server](https://github.com/denoland/deno/blob/3dff147d0ca1a2cd8d264d20a178d71cb38b1c4e/tools/hyper_hello.rs)'s performance against our own (dynamic language) web server. We've noticed that hyper has very bad tail latency - sometimes as much as 2 seconds.

You can see it here https://deno.land/benchmarks.html#max-latency
Screen Shot 2019-06-14 at 2 08 55 PM

We debugged this a bit, thinking at first it was our setup. But concluded that it was indeed a bug in hyper after making these changes: https://github.com/denoland/deno_third_party/compare/1902aba524c96f56c1dd654f04660a1fc3ebf80d...d8fb68ccfb72ad6a8b306dfcc3573efafa3c340f

cc @piscisaureus @carllerche

### PR DESCRIPTION
**Pull request by seanmonstar**
Adds a `YieldNow` helper, since I believe there may be a couple other places that could make use of this, like the accept loop in `SpawnAll`.

Closes #1828 

cc @ry

### CODE REVIEW

File: src/proto/h1/dispatch.rs [hunk 1]
```diff
@@ -112,21 +139,19 @@ where
...
-        } else {
-            Ok(Async::NotReady)
+        trace!("poll_loop yielding (self = {:p})", self);
+
+        match self.yield_now.poll_yield() {
+            Ok(Async::NotReady) => Ok(Async::NotReady),
+            // maybe with `!` this can be cleaner...
+            // but for now, just doing this to eliminate branches
+            Ok(Async::Ready(never)) |
+            Err(never ) => match never {}
```
Comment (olix0r) [inline src/proto/h1/dispatch.rs]: nit: whitespace `Err(never )`

**Comment by ry** [comment]
Thanks @seanmonstar, that seemed to have fixed the problem!

Screen Shot 2019-06-17 at 1 42 54 PM

(From https://deno.land/benchmarks.html)
